### ISSUE TITLE
Deadlock

### ISSUE THREAD

**Issue by DavidPetr** [amirkhaniansev/os-experiments#1]
In Semaphore project, producer and consumer functions may cause deadlock, first waiting for "empty_semaphore" then waiting "mutex" . I can advise you create array of HANDLEs, including mutex and semaphore, then use WaitForMultipleObjects .

**Comment by amirkhaniansev** [comment]
Deadlock would have been possible, if I placed **WaitForSingleObject(mutex, INFINITE)** before **WaitForSingleObject(empty_semaphore, INFINITE)**.
 
I think it will be helpful for you to read this **Wikipedia** notice: 

Here **proccess** can be read as **thread**.

"Note that the order in which different semaphores are incremented or decremented is essential: changing the order might result in a deadlock. It is important to note here that though mutex seems to work as a semaphore with value of 1 (binary semaphore), but there is difference in the fact that mutex has ownership concept. Ownership means that mutex can only be "incremented" back (set to 1) by the same process that "decremented" it (set to 0), and all other tasks wait until mutex is available for decrement (effectively meaning that resource is available), which ensures mutual exclusivity and avoids deadlock. Thus using mutexes improperly can stall many processes when exclusive access is not required, but mutex is used instead of semaphore."

**Comment by DavidPetr** [comment]
Ok 





воскресенье, 9 декабря 2018 г., 16:59 +0400 от notifications@github.com  <notifications@github.com>:

**Comment by amirkhaniansev** [comment]
I am closing this issue. If you have other questions, feel free to open a new one.

**Comment by DavidPetr** [comment]
DEAR Sevak. No, I don’t have more questions about that project. 



Отправлено из мобильной Почты Mail.Ru


воскресенье, 9 декабря 2018 г., 17:02 +0400 от notifications@github.com  <notifications@github.com>:
